server:
  port: 9010

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/razorpay-merchant-db

jwt:
  secret-key: asfd9asfdaoijfalkjl23u4oi5jlkjf98790890890ugojvakglsdfjn8yuh

webhook:
  secret-encryption-key: V7mQ2xK9pL4nR8sT1wY6aB3cD5eF0gH2jN7kM9qP4vA=
